# Generated by Django 3.0.3 on 2020-02-19 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=500)),
                ('lastname', models.CharField(default='', max_length=500)),
                ('email', models.EmailField(default='', max_length=500)),
                ('zip', models.IntegerField(default=0)),
                ('budget', models.CharField(default='', max_length=500)),
                ('laziness', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
