# Generated by Django 3.0.3 on 2020-02-20 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='user',
        ),
    ]
