# Generated by Django 3.0.3 on 2020-03-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
