# Generated by Django 3.0.3 on 2020-03-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deselect_Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('option1', 'Does not fulfill my dietary restrictions'), ('option2', 'Looks gross'), ('option3', 'Had a similar meal recently'), ('option4', 'Prefer not to answer')], default='', max_length=500)),
            ],
        ),
    ]
