# Generated by Django 3.0.3 on 2020-02-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0002_auto_20200223_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='dietary_restrictions',
            field=models.ManyToManyField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Peanut', 'Peanut')], default='', to='user_signup.User_Diet'),
        ),
    ]
