# Generated by Django 3.0.3 on 2020-02-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0002_auto_20200222_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_diet',
            name='dietary_restrictions',
        ),
    ]
