# Generated by Django 3.0.3 on 2020-02-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0002_remove_user_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='laziness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
