# Generated by Django 3.0.3 on 2020-03-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0002_user_data_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='user_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
