# Generated by Django 3.0.3 on 2020-02-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0003_auto_20200220_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='budget',
            field=models.CharField(choices=[('LOWEST', '<$40'), ('LOW', '$40-60'), ('MEDIUM', '$60-80'), ('HIGH', '$80-100'), ('HIGHEST', '>$100')], default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='laziness',
            field=models.CharField(choices=[('LITTLE', '1'), ('LESS', '2'), ('MEDIUM', '3'), ('HIGHER', '4'), ('HIGHEST', '5')], max_length=50),
        ),
    ]
