# Generated by Django 3.0.3 on 2020-02-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0004_auto_20200220_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='budget',
            field=models.CharField(choices=[('<$40', '<$40'), ('$40-60', '$40-60'), ('$60-80', '$60-80'), ('$80-100', '$80-100'), ('>$100', '>$100')], default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='laziness',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50),
        ),
    ]
