# Generated by Django 3.0.3 on 2020-02-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0005_auto_20200220_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='zip',
            field=models.PositiveIntegerField(),
        ),
    ]
