# Generated by Django 3.0.3 on 2020-02-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0006_auto_20200220_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_restrictions', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user_data',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, to='user_signup.User_Diet'),
        ),
    ]
