# Generated by Django 3.0.3 on 2020-02-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0007_auto_20200220_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='dietary_restrictions',
            field=models.ManyToManyField(to='user_signup.User_Diet'),
        ),
    ]
