# Generated by Django 3.0.3 on 2020-02-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0008_auto_20200222_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='dietary_restrictions',
            field=models.ManyToManyField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('None', 'None')], default='', to='user_signup.User_Diet'),
        ),
    ]
