# Generated by Django 3.0.3 on 2020-02-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0008_auto_20200220_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_diet',
            name='dietary_restrictions',
        ),
    ]
