# Generated by Django 3.0.3 on 2020-02-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0009_remove_user_diet_dietary_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_diet',
            name='dietary_restrictions',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan')], default='Vegan', max_length=10),
        ),
    ]
