# Generated by Django 3.0.3 on 2020-02-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0011_auto_20200220_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_diet',
            name='dietary_restrictions',
            field=models.CharField(default='Vegan', max_length=10),
        ),
    ]
