# Generated by Django 3.0.3 on 2020-02-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0012_auto_20200222_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='dietary_restrictions',
            field=models.ManyToManyField(choices=[('&#x27;Vegetarian&#x27', '&#x27;Vegetarian&#x27'), ('Vegan', 'Vegan')], default='', to='user_signup.User_Diet'),
        ),
    ]
