# Generated by Django 3.0.3 on 2020-02-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0012_auto_20200220_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, to='user_signup.User_Diet'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='laziness',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_diet',
            name='dietary_restrictions',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian')], default='Vegan', max_length=10),
        ),
    ]
