# Generated by Django 3.0.3 on 2020-02-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0013_auto_20200221_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_diet',
            name='dietary_restrictions',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan')], default='', max_length=10),
        ),
    ]
