# Generated by Django 3.0.3 on 2020-02-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0014_auto_20200221_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan')], to='user_signup.User_Diet'),
        ),
        migrations.AlterField(
            model_name='user_diet',
            name='dietary_restrictions',
            field=models.CharField(default='', max_length=10),
        ),
    ]
