# Generated by Django 3.0.3 on 2020-02-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0014_auto_20200222_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_diet',
            name='dietary_restrictions',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
