# Generated by Django 3.0.3 on 2020-02-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0017_auto_20200222_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='dietary_restrictions',
            field=models.ManyToManyField(choices=[('Vegetarian', 'Vegetarian'), ('[&#x27;Vegan&#x27;]', 'Vegan'), ('iihiyi', 'Peanut')], default='', to='user_signup.User_Diet'),
        ),
    ]
