# Generated by Django 3.0.3 on 2020-02-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0023_auto_20200222_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='dietary_restrictions',
            field=models.ManyToManyField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Peanut', 'Peanut')], default='', to='user_signup.User_Diet'),
        ),
        migrations.AlterField(
            model_name='user_diet',
            name='dietary_restrictions',
            field=models.BooleanField(default=True),
        ),
    ]
