# Generated by Django 3.0.3 on 2020-02-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0024_auto_20200223_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_diet',
            name='dietary_restrictions',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
